import {CONSTANTS} from './Constants';

const {SPACER} = CONSTANTS;
export interface ICharacters {
  ro: string;
  jp: string;
}

export const Characters: ICharacters[] = [
  {ro: 'a', jp: 'あ'},
  {ro: 'i', jp: 'い'},
  {ro: 'u', jp: 'う'},
  {ro: 'e', jp: 'え'},
  {ro: 'o', jp: 'お'},
  {ro: 'ka', jp: 'か'},
  {ro: 'ki', jp: 'き'},
  {ro: 'ku', jp: 'く'},
  {ro: 'ke', jp: 'け'},
  {ro: 'ko', jp: 'け'},
  {ro: 'sa', jp: 'さ'},
  {ro: 'shi', jp: 'し'},
  {ro: 'su', jp: 'す'},
  {ro: 'se', jp: 'せ'},
  {ro: 'so', jp: 'そ'},
  {ro: 'ta', jp: 'た'},
  {ro: 'chi', jp: 'ち'},
  {ro: 'tsu', jp: 'つ'},
  {ro: 'te', jp: 'て'},
  {ro: 'to', jp: 'と'},
  {ro: 'na', jp: 'と'},
  {ro: 'ni', jp: 'に'},
  {ro: 'nu', jp: 'ぬ'},
  {ro: 'ne', jp: 'ね'},
  {ro: 'no', jp: 'の'},
  {ro: 'ha', jp: 'は'},
  {ro: 'hi', jp: 'ひ'},
  {ro: 'fu', jp: 'ふ'},
  {ro: 'he', jp: 'へ'},
  {ro: 'ho', jp: 'ほ'},
  {ro: 'ma', jp: 'ま'},
  {ro: 'mi', jp: 'み'},
  {ro: 'mu', jp: 'む'},
  {ro: 'me', jp: 'め'},
  {ro: 'mo', jp: 'も'},
  {ro: 'ya', jp: 'や'},
  {ro: SPACER, jp: `${SPACER}-1`},
  {ro: 'yu', jp: 'ゆ'},
  {ro: SPACER, jp: `${SPACER}-2`},
  {ro: 'yo', jp: 'よ'},
  {ro: 'ra', jp: 'ら'},
  {ro: 'ri', jp: 'り'},
  {ro: 'ru', jp: 'る'},
  {ro: 're', jp: 'れ'},
  {ro: 'ro', jp: 'ろ'},
  {ro: 'wa', jp: 'わ'},
  {ro: 'wi', jp: 'ゐ'},
  {ro: SPACER, jp: `${SPACER}-3`},
  {ro: 'we', jp: 'ゑ'},
  {ro: 'wo', jp: 'を'},
  {ro: 'n', jp: 'ん'},
];
